FROM golang:1.17

# Create a new user
# RUN useradd -m appuser

# Install air for hot-reloading
RUN go get -u github.com/pilu/fresh

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

COPY fresh.conf /app/fresh.conf

# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Change the owner of the /app directory
# RUN chown -R appuser:appuser /app

# Use the created user
# USER appuser

# Expose the application's port
EXPOSE 6002

# Start air for hot-reloading
CMD ["fresh"]