FROM golang:1.19

# Install fresh for hot-reloading
RUN go install github.com/pilu/fresh@latest

# Set the working directory
WORKDIR /app

# Set the environment variable
ENV GO111MODULE=on

# Copy go.mod and go.sum files
COPY ./pg-api/go.mod ./pg-api/go.sum ./pg-api/

# Download dependencies
RUN cd ./pg-api && go mod download

# Copy the entire project
COPY . .

# Expose the application's port
EXPOSE 6002

# Start air for hot-reloading from the pg-api directory
CMD ["sh", "-c", "cd pg-api && fresh -c fresh.conf"]
# CMD ["cd", "pg-api", "fresh"]
