name: Test goapistac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

env:
  GO111MODULE: on

jobs:
  test:
    runs-on: alpine-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest

    - name: Install build dependencies
      run: |
        apk add --no-cache make git
    - name: Test the application
      run: |
        go test -v ./...